export const SELECT_CATEGORIES = [
    { label: 'Arte e design', value: 0 },
    { label: 'Beleza', value: 1 },
    { label: 'Bibliotecas e demos', value: 2 },
    { label: 'Casa e decoração', value: 3 },
    { label: 'Clima', value: 4 },
    { label: 'Comer e beber', value: 5 },
    { label: 'Compras', value: 6 },
    { label: 'Comunicação', value: 7 },
    { label: 'Corporativo', value: 8 },
    { label: 'Criar os filhos', value: 9 },
    { label: 'Daydream', value: 10 },
    { label: 'Educação', value: 11 },
    { label: 'Encontros', value: 12 },
    { label: 'Entretenimento', value: 13 },
    { label: 'Esportes', value: 14 },
    { label: 'Estilo de vida', value: 15 },
    { label: 'Eventos', value: 16 },
    { label: 'Ferramentas', value: 17 },
    { label: 'Finanças', value: 18 },
    { label: 'Fotografia', value: 19 },
    { label: 'Humor', value: 20 },
    { label: 'Livros e referências', value: 21 },
    { label: 'Mapas e navegação', value: 22 },
    { label: 'Medicina', value: 23 },
    { label: 'Música e áudio', value: 24 },
    { label: 'Notícias e revistas', value: 25 },
    { label: 'Personalização', value: 26 },
    { label: 'Produtividade', value: 27 },
    { label: 'Realidade aumentada', value: 28 },
    { label: 'Reproduzir e editar vídeos', value: 29 },
    { label: 'Saúde e fitness', value: 30 },
    { label: 'Social', value: 31 },
    { label: 'Turismo e local', value: 32 },
    { label: 'Veículos', value: 33 },
    { label: 'Jogos', value: 34 },
]
